### PR TITLE
Fix css to avoid horizontal scrolling in the SQL panel

### PR DESCRIPTION
**Pull request by corehack**
Simplest fix for #281

### CODE REVIEW

**Comment by mmerickel** [comment]
Any chance you can submit before/after screenshots? Otherwise I'll spin this up at some point this week but if I could see it I'd just click merge. Thanks!

**Comment by corehack** [comment]
I noticed there are still some differences between how different browsers break the words, but the main issue of horizontal scrolling should be fixed. Will see if we can get consistent work breaking

**Comment by corehack** [comment]
I have only checked in Firefox and Chomium. I don't have Windows to check in IE, Edge, etc
There's a small issue that query args inside queries can be broken, but it's not because of CSS, but because of incorrect templating. For example, if you have `session.id=%(session_id)s` in a query, the part after percent sign can be broken, because `=%` inside HTML is contained within `<span>` tag, so browsers can rightfully assume it's not 1 single word and break it.
I will upload pictures before/after

**Comment by corehack** [comment]
You can check screenshots before and after here http://imgur.com/a/c5nYu (firefox on linux)

**Comment by mmerickel** [comment]
LGTM, thanks!

**Pull request merged**
