### PR TITLE
Add filtering for requests list

### PR DESCRIPTION
**Pull request by dz0ny**
See #111 

Library can be used for other panels as well.   

Preview:
image

### CODE REVIEW

**Comment by dz0ny** [comment]
@mmerickel this is here for to long... Can you please respond...

**Comment by mmerickel** [comment]
Sorry @dz0ny. I think this PR is fine but of limited use. The toolbar only shows 10 requests max by default on the screen and that is done server-side. This means you're filtering between 10 requests. What's the point? Is the idea that you type in a filter and then it shows "no requests" until the one that matches shows up? I don't see any code that updates the filter as new requests come in.

**Comment by mmerickel** [comment]
I just confirmed that the filter is not controlling updates to the page. If this were updated such that when new requests came in they were properly filtered then I would accept it. Steps to reproduce:

1. `env/bin/python demo/demo.py`
2. Open the browser to the `/ajax` endpoint.
3. Open the toolbar and type "ajax" into the filter.
4. Wait 15 seconds and observe that "/" and other old requests are visible because they were not properly filtered.
5. Hit "enter" on the filter to update it again.

Step 5 should not be necessary.

**Comment by mmerickel** [comment]
Closing from inactivity. Please fix the above issue and I'm happy to reopen/merge this feature.

**Pull request closed without merging**
