### PR TITLE
Defer response headers processing to a finished callback

### LINKED ISSUE #309: Response headers in the headers toolbar could be incorrect
Since it's possible to modify headers after toolbar tween finished processing, displayed headers could be incomplete or incorrect. Most common example is when headers are modified by a response callback as using callback is the universal way of working with headers, that works regardless of the way response is   generated.
If https://github.com/Pylons/pyramid/issues/2622 is fixed (but that is unlikely as far as I see), this issue could be fixed also by moving the response callback tween below toolbar.

### PR DESCRIPTION
**Pull request by corehack**
Fixes #309

### CODE REVIEW

**Comment by corehack** [comment]
I still need a reference to an actual response object. Inside __init__ there's no response yet (too early) and in the finished callback no response either (too late).

**Comment by corehack** [comment]
The only worry with this approach is, if it's possible that `__init__` will run, but `process_response()` will not, then there's no reference to response and we get an error. I'm not sure if we need to account for that by using getattr or something. The initial approach by referencing the request was better in this sense

**Comment by mmerickel** [comment]
There is really no point in trying to be the last finished callback as even the first one does not have access to the response in general and if anyone is figuring out how to access it and changing it there, I do not care if the toolbar tracks those changes or not. Adding the jump logic here is too defensive for this particular feature.

Option 1: Just tweak the panel to add a `NewResponse` subscriber via `config.inject_parent_action`. It will be guaranteed to be the last subscriber added in most cases and that thing executes after response callbacks.

Option 2: Use a single finished callback and hang onto the response from `process_response` like you're doing now and pull the headers when it is invoked.

**Comment by mmerickel** [comment]
LGTM, thanks! We could initialize the `self.data` earlier but I can't envision a scenario in which the current code breaks so I'm not too worried about it. Right now we call `process_response` even if the response is the debugger.

**Pull request merged**
