### PR TITLE
Introduce validation for the Host header

### LINKED ISSUE #274: Make sure that we're not vulnerable to DNS rebinding attack
It started with [Rails](http://benmmurphy.github.io/blog/2016/07/11/rails-webconsole-dns-rebinding/); now there was CVE 2016-9014 in Django; someone should make sure that pyramid_debugtoolbar is not vulnerable. This attack allows a malicious site being opened in any browser to access the debug console - the *hostname* of the request must be validated.

### PR DESCRIPTION
**Pull request by a3kov**
Fixes #274.

### CODE REVIEW

**Comment by corehack** [comment]
Hmm, we still have an issue that toolbar link from the handle uses the same address as the main project. If these two addresses are different, we may need to change the link target

**Comment by corehack** [comment]
I could automatically add main domain the dev environment is using to the accepted domains whitelist. The problem though, is that there's no such setting - it depends on the currently used web server.
So the only reliable way it to always use our accepted domains whitelist for the toolbar iframe - first domain in the list, perhaps.

**Comment by corehack** [comment]
The only remaining thing - we assume that toolbar domain is available under same scheme and port as the main app. Even if this is true by default, generally it could be different and depends on the webserver configuration. However I feel adding these settings would only complicate things - we don't need fully featured virtual hosting - we are just protecting toolbar from rebinding attack.

**Comment by mmerickel** [comment]
If this were renamed to `debugtoolbar.allowed_hosts` and supported being set to an empty string or `*` or something to turn it off but defaulted to localhost then I would likely accept it. Any thoughts on dusting this off? The only other change is that I'd prefer the check for ipv6/ipv4 ipaddresses used the `ipaddress` module to parse them instead of needing to maintain this parsing code.

**Comment by ergo** [comment]
@a3kov any news on this?

**Comment by a3kov** [comment]
@ergo
Nope, no news. Been busy with Django all the time .

**Pull request closed without merging**
